src/lib.rs
Applications no longer require a riker.toml. The min required default values are built-in.
=> Config fix

config/riker.toml
Include explanation and example (commented out).
=> Add commented `filter` to default riker.toml

src/lib.rs
As per the issue: a feature has stabilized and therefore there's no need to opt-in to it.
=> remove now-stable feature opt-in - issue #30

Cargo.toml, src/actor/actor_cell.rs, src/actor/selection.rs, src/system/system.rs, src/validate.rs, tests/selection.rs
=> Fixed absolute paths

src/actor/actor.rs
The Actor implementation for Box<Actor> calls apply_event in its replay_event wrapper.
=> Make replay_event on Box<Actor> actually call replay_event

src/actor/channel.rs, src/system/system.rs
ActorRefFactory is implemented twice. Once for ActorSystem and once for &ActorSystem. Because the implementations are exactly the same, i think the second one is not needed.
=> Removed duplicate ActorRefFactory impl

src/validate.rs
Change Kleene star to Kleene plus in regex.
This fixes the issue that names could be empty strings.
=> Fix regex in validators.

src/kernel/kernel.rs, src/kernel/kernel_ref.rs, src/lib.rs
This PR switches from await! macro to .await keyword which does not require a separate feature gate.
It also removes unnecessary dependency on unstable `bind_by_move_pattern_guards` feature.
=> Switch to .await syntax. Reduce number of unstable feature flags.

tests/system.rs
Remove feature arbitrary_self_types from one of the tests because it isn't needed. (compiles & runs without it).
=> Remove feature arbitrary_self_types

.gitignore, Cargo.toml, config/riker.toml, src/actor/actor.rs, src/kernel/kernel.rs, src/kernel/mailbox.rs, src/kernel/provider.rs, src/lib.rs, src/system/logger.rs, src/system/mod.rs, src/system/system.rs, tests/logger.rs
This PR replaces `log` crate by the `slog` crate. All code was written with a backward compatibility in mind. When `slog::Logger` is not passed to actor system via the `SystemBuilder`, then behavior and log messages format stays the same as was before this PR.
Example of how `slog` can be passed to riker.
```rust
#[macro_use]
extern crate slog;
extern crate sloggers;
use sloggers::Build;
use sloggers::terminal::{TerminalLoggerBuilder, Destination};
use sloggers::types::Severity;
let mut builder = TerminalLoggerBuilder::new();
builder.level(Severity::Debug);
builder.destination(Destination::Stderr);
let logger = builder.build().unwrap();
let sys = SystemBuilder::new()
.log(logger)
.create().unwrap();
```
=> Use slog as a logging subsystem

src/actor/actor_cell.rs, src/system/system.rs, src/system/timer.rs
This MR introduces `Instant` for time tracking in the timer, replacing the before used `SystemTime`. 
Closes #42.
=> Use Instant for time tracking instead of SystemTime

src/actor/actor_cell.rs, src/actor/channel.rs, src/actor/mod.rs, src/actor/props.rs, src/actor/selection.rs, src/kernel/kernel_ref.rs, src/kernel/mailbox.rs, src/kernel/provider.rs, src/kernel/queue.rs, src/lib.rs, src/system/logger.rs, src/system/mod.rs, src/system/system.rs, src/validate.rs, tests/system.rs
Resolved `cargo clippy` errors and warnings:
```
warning: redundant field names in struct initialization
--> src/actor/actor_cell.rs:576:13
|
576 |             interval: interval,
|             ^^^^^^^^^^^^^^^^^^ help: replace it with: `interval`
|
= note: `#[warn(clippy::redundant_field_names)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_field_names
warning: redundant field names in struct initialization
--> src/actor/actor_cell.rs:578:13
|
578 |             sender: sender,
|             ^^^^^^^^^^^^^^ help: replace it with: `sender`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_field_names
warning: redundant field names in struct initialization
--> …
```
=> Address `cargo clippy` errors and simple warnings

Cargo.toml, config/riker.toml, src/lib.rs, src/system/system.rs
Changes the default pool_size for the thread_pool to two times the cpu count.
This should give pretty decent default performance without the need to configure something.
=> Thread pool config and defaults

riker-macros/tests/macro.rs
Removed a use importing a non existing macro in macro tests, which previously was not being checked by the compiler.
=> removed old att macro import

src/actor.rs, src/actor/actor_ref.rs
`Sender` is encouraged over underlying `Option<BasicActorRef>`.
=> using the type alias Sender in place of Option<BasicActorRef>

.gitattributes, rustfmt.toml
This fixes #107 by always using native newlines on the users machine, but converting to LF when commiting.
=> #107 Set newline style in .gitattributes and change newline_style in rustfmt.toml

src/kernel/provider.rs
Currently the register method checks if a path is already in the dashmap. If it is, it calls replace which returns the old value if one was present. If the old value was present, it replaces the old value again.
Because the value is always `()` and replace already handles the case where a path is already registered, this method can be simplified which should make reasoning about the code easier.
This should also make it a bit faster, because it removes duplicate calls to replace and one one unnecessary call to contains_key.
=> Simplify provider::register()

src/actor.rs, src/actor/actor_cell.rs, src/actor/uri.rs, src/kernel/provider.rs
Removes the actor ID because it isn't used anywhere except to check if an actor is the root. Also if riker is used on systems where usize is 32 bit or smaller, there is a chance that the actor id wraps around and multiple actors could end up with the same id.
The old is_root checks if the actor id is 0. In case of an overflow this could happen more than once.
The new is_root function uses the actor path, because it is already guaranteed that there can't be a second actor with the same path.
=> Remove actor id

riker-macros/Cargo.toml
There don't seem to be any incompatible changes, this brings it to the same version used by most other crates
=> Switch to syn, quote, proc-macro2 version 1.0

README.md
I just tried riker for the first time, and couldn't get the example in the readme to compile. Then I noticed the Cargo.toml version was wrong, so I changed it. The example compiles now.
=> Changed Cargo.toml version in README.md

Cargo.toml, riker-macros/Cargo.toml, src/actor/actor_cell.rs, src/kernel/provider.rs
This is basically the same as pr #132, just resolved the conflict. I ran pre-commit, all tests pass, all examples seem to work fine and no warnings are thrown on build. I tested it integrated in a project that works with the current release version, and this change continues to work properly and as expected (on macOS). I did remove a couple of the changes proposed by @bfrog because there is apparently no longer any need for the Dashmap iterator and no reason to submit code that has warnings. ;)
I guess it would probably be good to add a test to check this deadlock issue though, but I am not sure how to replicate that.
Closes #131  
Closes #122
=> fix(dashmap): use stable dashmap

src/actor.rs, src/lib.rs, src/system.rs, src/validate.rs, tests/actors.rs
according to https://doc.rust-lang.org/std/error/trait.Error.html#method.description
Error description function is "Deprecated since 1.42.0: use the Display impl or to_string()"
=> fix clippy::to_string_in_display issues
